-- MySQL Script generated by MySQL Workbench
-- Thu Mar 27 17:59:06 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema api
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `api` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `api` ;

-- -----------------------------------------------------
-- Table `api`.`sh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api`.`sh` (
  `co_sh4` INT NOT NULL,
  `no_sh4_por` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`co_sh4`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `api`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api`.`pais` (
  `co_pais` INT NOT NULL AUTO_INCREMENT,
  `co_pais_isoa3` VARCHAR(3) NOT NULL,
  `no_pais` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`co_pais`))
ENGINE = InnoDB
AUTO_INCREMENT = 1001
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `api`.`municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api`.`municipios` (
  `co_mun` INT NOT NULL AUTO_INCREMENT,
  `no_mun` VARCHAR(40) NOT NULL,
  `sg_uf_mun` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`co_mun`))
ENGINE = InnoDB
AUTO_INCREMENT = 3457304
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `api`.`exportacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api`.`exportacao` (
  `cod_exportacao` INT NOT NULL AUTO_INCREMENT,
  `co_ano` INT NOT NULL,
  `co_mes` INT NOT NULL,
  `co_sh4` INT NOT NULL,
  `co_pais` INT NOT NULL,
  `sg_uf_ncm` VARCHAR(2) NOT NULL,
  `co_mun` INT NOT NULL,
  `kg_liquido_expt` INT NOT NULL,
  `vl_fob_expt` FLOAT NOT NULL,
  `valor_agregado` FLOAT NOT NULL,
  PRIMARY KEY (`cod_exportacao`),
  INDEX `co_sh4` (`co_sh4` ASC) VISIBLE,
  INDEX `co_pais` (`co_pais` ASC) VISIBLE,
  INDEX `co_mun` (`co_mun` ASC) VISIBLE,
  CONSTRAINT `exportacao_ibfk_1`
    FOREIGN KEY (`co_sh4`)
    REFERENCES `api`.`sh` (`co_sh4`),
  CONSTRAINT `exportacao_ibfk_2`
    FOREIGN KEY (`co_pais`)
    REFERENCES `api`.`pais` (`co_pais`),
  CONSTRAINT `exportacao_ibfk_3`
    FOREIGN KEY (`co_mun`)
    REFERENCES `api`.`municipios` (`co_mun`))
ENGINE = InnoDB
AUTO_INCREMENT = 7683143
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `api`.`importacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api`.`importacao` (
  `cod_importacao` INT NOT NULL AUTO_INCREMENT,
  `co_ano` INT NOT NULL,
  `co_mes` INT NOT NULL,
  `co_sh4` INT NOT NULL,
  `co_pais` INT NOT NULL,
  `sg_uf_ncm` VARCHAR(2) NOT NULL,
  `co_mun` INT NOT NULL,
  `kg_liquido_expt` INT NOT NULL,
  `vl_fob_expt` FLOAT NOT NULL,
  `valor_agregado` FLOAT NOT NULL,
  PRIMARY KEY (`cod_importacao`),
  INDEX `co_sh4` (`co_sh4` ASC) VISIBLE,
  INDEX `co_pais` (`co_pais` ASC) VISIBLE,
  INDEX `co_mun` (`co_mun` ASC) VISIBLE,
  CONSTRAINT `importacao_ibfk_1`
    FOREIGN KEY (`co_sh4`)
    REFERENCES `api`.`sh` (`co_sh4`),
  CONSTRAINT `importacao_ibfk_2`
    FOREIGN KEY (`co_pais`)
    REFERENCES `api`.`pais` (`co_pais`),
  CONSTRAINT `importacao_ibfk_3`
    FOREIGN KEY (`co_mun`)
    REFERENCES `api`.`municipios` (`co_mun`))
ENGINE = InnoDB
AUTO_INCREMENT = 7056315
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
